### ISSUE TITLE
Sources for USB code for PIC18F2550

### ISSUE THREAD

**Issue by ashwinm76** [oh2aun/flashforth#4]
Hello,

I'm trying FlashForth 5.0 on a PIC18F2550 in USB mode. When I connect the device to a windows machine, I see the device appear as COM5 in the device manager. However, windows flags an error ("This device cannot start (Code 10)").

Looking through the sources for some clues, I find that much of the USB code is in the precompiled FF_USB_18F2550.lib library. 

I would like to try and recompile the USB library using Microchip's latest USB library sources, so that I could debug USB problems. However, the git repository doesn't seem to contain any files with the USB CDC endpoint descriptors etc. Where are the sources where the USB descriptors are declared? How do I recompile this library?

Thank you.

**Comment by oh2aun** [comment]
Hi,
Since the files are copyright microchip I did not put them on github or sf.

**Comment by ashwinm76** [comment]
I guessed as much. I was hoping that some parts of it (e.g. the parts where you initialize the USB descriptors for USB CDC functions, the USB callbacks etc.) were written by you (i.e. not copyrighted) and could be made available, so that one could rebuild everything by putting them together with the latest MLA libraries from Microchip. Oh well..

**Comment by oh2aun** [comment]
I will fix the windows issue when I have some time.

I removed USB code to make the image smaller. I removed too much...
Linux still works.

**Comment by ashwinm76** [comment]
Ok, I'll wait till the issue is fixed. Thanks for responding :-)

**Comment by oh2aun** [comment]
Just pushed a version that also works on windows(7).

It more compact and the source code is included (asm).

Tested on 18f14k50 and 18f2550.

BR Mikael
