### ISSUE TITLE
asm2 sbi sbi sbic sbis

### ISSUE THREAD

**Issue by mike290** [oh2aun/flashforth#5]
asm2.txt is very cool but I had problems with cbi and sbi producing incorrect hex. Line 24 is incorrect. It should be:
[ 0f8.3 , 007.0 , ] \ 04 xxxx.xxxx.dddd.dbbb cbi sbi sbic sbis

**Comment by oh2aun** [comment]
Thanks for reporting it. I'll fix it.
Mike

**Comment by oh2aun** [comment]
Fixed.
